"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['ServerInstallAgent.py']
DATA_FILES = ['TuneConnect Server.prefPane']
OPTIONS = {'argv_emulation': True, 'plist': {
		'CFBundleIdentifier': 'net.tuneconnect.ServerInstaller',
		'CFBundleVersion': '2.0',
		'NSHumanReadableCopyright': u'\u00A9 The TuneConnect Project, 2008'
	},
	'iconfile': 'TuneConnect-Server.icns'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
