// This file was generated by Dashcode from Apple Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateInfoButton('info', { frontID: 'front', foregroundStyle: 'white', backgroundStyle: 'black', onclick: 'showBack' });
    CreateGlassButton('done', { text: 'Done', onclick: 'showFront' });
    CreateText('status', { text: 'Connecting...' });
    CreateText('text1', { text: 'Server' });
    CreateButton('playButton', { text: 'Play', onclick: 'playPause', rightImageWidth: 1, leftImageWidth: 1 });
    CreateButton('nextButton', { leftImageWidth: 1, onclick: 'nextTrack', rightImageWidth: 5, text: unescape('%3E%3E|') });
    CreateButton('backButton', { leftImageWidth: 5, onclick: 'prevTrack', rightImageWidth: 1, text: unescape('|%3C%3C') });
}
window.addEventListener('load', setupParts, false);
